=== kirol/python/json/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "CreationTime": {
      "type": "string"
    },
    "DriveIdentify": {
      "type": "object",
      "properties": {
        "Manufacturer": {
          "type": "string"
        },
        "ModelId": {
          "type": "string"
        },
        "Serial": {
          "type": "string"
        },
        "Firmware": {
          "type": "string"
        }
      },
      "required": [
        "Manufacturer",
        "ModelId",
        "Serial",
        "Firmware"
      ]
    },
    "SmartData": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "value": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "value"
        ]
      }
    },
    "VendorData": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "VendorId": {
            "type": "string"
          },
          "Data": {
            "type": "string"
          }
        },
        "required": [
          "VendorId",
          "Data"
        ]
      }
    }
  },
  "required": [
    "CreationTime",
    "DriveIdentify"
  ]
}

=== kirol/python/payload.json
{
  "CreationTime" : "2015-11-14T06:06:46Z",
  "DriveIdentify" : {
    "Manufacturer" : "WD",
    "ModelId" : "WDC WD10EURX-63C57Y0",
    "Serial" : "WD-WCC4J1836074",
    "Firmware" : "01.01A01"
  },
  "SmartData" : [ {
    "id" : 200,
    "value" : "000000000000"
  }, {
    "id" : 199,
    "value" : "000000000000"
  }, {
    "id" : 198,
    "value" : "000000000000"
  }, {
    "id" : 197,
    "value" : "000000000000"
  }, {
    "id" : 196,
    "value" : "000000000000"
  }, {
    "id" : 9,
    "value" : "0E0300000000"
  }, {
    "id" : 194,
    "value" : "2F0000000000"
  }, {
    "id" : 193,
    "value" : "480000000000"
  }, {
    "id" : 7,
    "value" : "000000000000"
  }, {
    "id" : 192,
    "value" : "DF0000000000"
  }, {
    "id" : 5,
    "value" : "000000000000"
  }, {
    "id" : 4,
    "value" : "E40000000000"
  }, {
    "id" : 12,
    "value" : "E40000000000"
  }, {
    "id" : 3,
    "value" : "440F00000000"
  }, {
    "id" : 11,
    "value" : "000000000000"
  }, {
    "id" : 1,
    "value" : "000000000000"
  }, {
    "id" : 10,
    "value" : "000000000000"
  } ],
  "VendorData" : [ {
    "VendorId" : "ifhm",
    "Data" : "H4sIAAAAAAAAAO2df3AUZxnHkyXsJgQyd3Dv3rOXhNwllz3bhIRNILkDDkIYEuJAW9LwY2iQkvBD\naCk1Uk2ggO1oFKxT1CJgS6e1rdCKlhnbqWIYahU6dWrVqdMppeDwq2h0WlBqtdDq8z7vrncXD+g/\n/uHwMPOZvbzv8733/e7uXWa/G95tbpvdMUavhEVGH8yd1nf81qbKG8MNlZ8K5o4Gny7+izDSi+xH\ncgwBXy4U8CYIGKgT8KVvC4BtAqJI/jMC/vJyStfaHL/51pmR9shUuybsRKgtODJYvG6k7C+FwYfd\n2jwBr/8wpTs4SsDbhrBC+4LwOUPovkIf/F0XFRew/bwRsKYPBKHXCOiXWnxwWA9USM1rXw2CH7eR\nh4NQrCn9YWzrM0Servvgsi7KR2lKH8ea9UZg+APjlX5xR6u9C+ck8VUKWIXz6dIfBz++fgL9btYH\n4eLwMsLXmNbfmOqfmV9GDO0/ZPhhE/a/c1knfBPT+iem9FVTcokr9X+xJZeQ/d15Y2Cp2/8DoxRf\nD8JTiwsJX3mavjw1/sVIkvBVpfVXpd4/23FnGIZhGIZhGOZ/w+KOjtQ1iNEAIV3o9boFvmQD5OgB\nq14/DX5ogDN4vVKvn0tdjxhRKMkTekQvLfElowBFASuiv1fihygM5gQq8LVPXpfcl69q5ftG9OLQ\nlWrlNco5eZ1i2FRbQe9rU20F1dpUi6998nqlWl6zfIJaee3S2/LJak/idcwpeS1jOADobQLVOlQ7\ngWodqsXXPnlN49TgdY0Rp/dNUm2capNUG6dafO3j84xhGIZhGIZhGIZh/v9oma4yk++6mcmyGG7B\n3SYb4L6IAD+251QKyk7aynGL7T+uEPD+8DJCZiI9lZcsH0Sxboslc5HL4f2oi8JA+RZLZiNNFadQ\nFwW7pj8kc5T73SyF6rH/R9ElpKuNtJIuWI712K7Gi+I8Llnn0nKVguh+nKe7TdqwMNxp+bG9rRy3\n2P5uOY6P7XK86rSMRc3ThqcqO0JStzWM4xjyZ6zH9oHyFtLVRrZYz7XkwnNu3kLzw37lz3bnmRpP\nzdOGnTXnQ6fSshe1Px13PAf+RjoHzlacD8kMZmu4I+TH9rW1rxTLDMbLYZS/uJpvMo71uB+xXe2X\nuDvPOM2fz2OGYRiGYRiGYRiGYRiGuX5pn9Fqy3x3t5vx+vTd03LvEjD6YolbM9q6ZagOZN0M/Xvz\nBNi3lbrtujV/aF1S1v2usHCSgMYT3v99qrTuGVLnp3HnOQ8tFzB/tvd+Z6BiaB2Ne1YPNgk4frfP\nbf8AkkPraNzbRnSGBdStDrrtvwRnSJ3Mp7+hqaxZ+h5cJWD9PwNuf5FVom+CvAzfUfJd2Ckg+bUy\nt32K1YZ1d2X4jpLvs3EBr0739mOV9Vl9I6zI8B0l37PuFPDrJ7y6gFWlb4ZlGb6j5Lt7joC9q8e4\n7e9AJY67PMN3lHyviggY87Tn+yWYqPfAprQ6ma9/JT/l+49fEPDsTZ7vfAv0PijJ4vvBJQIOTfJ8\n11ktOP7qLL6PTRbQ+Z53HMdZ3frnYWkW3z3oe9+T1/bdjL7rlqR8R3HcZVl870Df4YGU7wb0fXta\nnbw/MOjeI5C+j/YIePHF4H/85OrLoTDDt02+9+Hxjoe9/TPVsnD/lGb4tsl3sBnHOOad53PwPF8G\n6zJ82+Q7gb4Lvn813zb5bp8twJjj+T6LvjdDd4Zvm3wfQd9dRzwfr6LvjRn7W97f2OPe45C+y9cJ\n+Mchz89Eq1jvhdwsvuPou+7Rq53nyrdoEbD9Bc/PfGsNzvOOLL73rRUQ3O7VCfLdncX3PDzeW9de\n7TxXvn+Dvuf+PNN3V1qdvD/zQkvKdw/6nnrU8z0BP9+9oGXxPYjn+cqve/NMWk04flcW33sTAm54\n2qtbcEXfDh7vqc9e+3jfi74vrLq27wvoe85VfMv7SxsXqXtM0ncdfr5PvJ/5vTYsw7dDvuej759V\ne8e73pqJ81yV4dsh3734vbYh4vmpsVbg5yzDD407zylF33v3XM23Q75z0HfnCs/3uSyfb4d8F9UI\neP4Nz/dr0Ii+0+vk/bHdteoemfT9CzzeXSO8+karVN8w5Ps8Tr4XLhbw8eNee8ISeF4EM3zHyffH\nrXi8m7zvtYXWBqzry/AdJ98fou9xRzzfplU99DjSuGf1x9D362s83yfxePcNOd5x8j0JfTtvpnzH\nh/weYRiGYRiGYRiGYRiGYRiGYRiGYRiGYRiGYRiGYRiGYRiGYRiGYRiGYRiGYRiGYRiGYRiGYRiG\nYRiGYRiGYRiGYRiGuV7YnXquws5pusir74+Bb0rDzpgesOr7J4O/uGFnWA9U1PfHYXxbsy1rH3Wf\nw1Bj4jbUAO1yO6UBThSo5yRoQSF1MGCq5xwswJ/lMwxecZ9j8NeCNtRFYYaZh7ooTDXvofX2f2re\ni7oofGR20Hr5ZcFx9AyAfvc5ALVmgHSNZhHpbjA3ke4n5mbSHTCDpKsOjoU/X9ah+yO1jr4wq1Fn\nu/O04YOCkbTu+R7zJtTZsNG8kdYtN4MdsHdKLiF1fyq4hXTfMeeSrtrcQLqD5t2ke9ucSLpoUKc1\n3C+667i/XNBDum+Z80hXZfaS7pSsR912s450/zLnwKZFhXDAXQf9QsEs1DkwyxyGOgfeKCildcpP\nmyNQ58CHZhWtM/6u2UlriB911xHXzATq4tBmaqiLQ6XZQ+t87zIfQV0cjpjTaJ3uU2YTn/MMwzAM\nwzAMwzAMwzAMcx0zY1arLfPdfjfjPaypjPchTWW8JZrKeH+rqYxXtsuMdxduf6WVQVmOymqPa6WU\n1W7T/JTVBrRSymoPaMMoq+3SDMpq79CK4aX8Mjg5Vul+r+WhLobtJaiLgV8bi7qYq4vBSg1QFyOd\nzHfPuBnvH7QxlLmu0UZT5qp0NjypWZS5ynnIzPWbOA+Z7y5PqqxWzdOGHZpJOjVPG57Xikgn30/q\ndmhByncPNiudmqft7hcbxmJ/+niebhv6kPnuYytUxntMZuAhB/eXjzJekPPC9mdw/jLjle0y470P\n5/FWbRJWjpMZb8KdZ8LVJVx/CXe/JGj+/mSC5snnMcMwDMMwDMMwDMMwDMNcv4yfsdCW+e4Dbsb7\naUNlvJ8xVMYbNlTGK9tlxnunoTLeftzKfPctN+OtNgop4203LMp46w2gjFfpotBtlFDG+4ih8t3b\ny6Qu5upiri4GI41cyniVLgZLjbGU8UqdzHfXF6nM1TYc9Xe8pLNhuFFEmevNho8yVzWeTTqZ7552\nM141ng0LDJUNq/FSOuVP6WS+W7Iwuy7XGJF1vPsNP+W7fd0q4203RlHGq+bpuPvFwf1rUcar/Dmo\nb6B898EmlfEqXQLHNejveEcbkynjVfslARuMPPo73h1GiM9jhmEYhmEYhmEYhmEYhrmOybnGv38D\nUAiyXQDYAAA="
  }, {
    "VendorId" : "drm",
    "Data" : "H4sIAAAAAAAAAO2dCXyMx/vAhbqp+2pa6qY/1N2iqFIhaBJHks0ms9U49pULQagzdVVdRSWIK/VT\n9UebxE5WNHFFqu5kX0IccYSq0lYo/amG/zPvzO6+u9lNXhupiNnP5/t55n3eeed5Z/Y9ZuaZmTfZ\ncOXOKyVLsF95pxJ2fvtL7C7hVKKkha5UCf570X/dqn3xUIuycD8k4LGty21TBd+aowq+PDtYdQoL\nSGRE3mgSyMLqayeDfdM2h71/fBtlQvtA0G99NFX3Acj9GhFP9xXxaT8RJ3wk4uuuIp4P4Rp9RZyh\nFnGHL0Rc9piIe78v4ugJIo6qLeINQ0UcXlnEKjh2XEURTxko4l5dRPwE0jnzDqQ9WMR1Woj4FuwX\nmol4JOhHNoF4sD2xKRyjErHfBRFX8RHxvbMi/gvsRb9rwPXgOI9TIk4i8UURH/YWccpxEQ+CeAmH\n4Tg4PvxHSBP2hx8UcSnY7nYAbMN2jX2QPpxvVo6I34B8RYJ8G2TrvyFNkLVAPgG7U++KWIR8br4K\n5wn661ki7glyIcgokEmXRewC+QuIhHODdO+vpMcngewP9tYtF3EXkK2/FHEn0B8GuQDO7+ZiER+H\n7UFQXhqp3OueGQ5Siw7hsSC/XPqT9H+MA6YTfUAHsh2b0bW1juh7Ddxn1nWmug/luvZUpwKd8FV7\nKa2MNlTnR+JNJfEa67a2ozpE4pmuB05RQKv+8OcwZMBTIDw6134DTkZHZNtHgSm83DgcDofD4XA4\nHA6Hw+E8X9SPX+vP+jOmsD4Mi/4OdF/q+9KybdL35UbCS8SkRFTDFC/iNsgqZ6T+OEm35lA8L18O\npyiREfPx7yL+FIVC+DpQGvgLaAl0A9rpBJQDMlkvoCSQO/Q03miQ80Geh3v6EMiTIB+CXAkyC+Rm\nkCdB9gIZBbJ8PO37bBhP00+JFdBxkDdAbgM5E+Q9kA1ANgA5IIbGL3geo/4n4tkeufXD++zDAzSF\nXb7ndwno9yQBXcr1HLUkaXthnkcqqh1jb99vD57f9fe9V824PrLtx9/M+cFVk4YD0Bk8En2FI6If\n4NEoE4dA2WnRHNwZ9f1VyAzs4Ia+PRKcK72o1QL6/H/Bdu1d2JlbdyqP8zPY/M8CLLa3F+X7u1NE\ndKsjMinpq8ygMlwt4rL/0Pw9ZvvW93z3BX6WnbL6P43/3TmmT8snvrX+nFU6hBt5xDdYxTfqD9qJ\n35VtpzJ5GvgWWBxjP49nYspU8cdB6BF7Tm/A9Lm5F9PnqQq4X4T+EwPujoZY+b/m8/cuh8PhcDgc\nDofD4XA4HA6Hw+FwOBwOh8PhcDgcDofD4XA4HM4LR2oMnhGOA6TxoGS+AJkjkGEao9vYIu5KHJJP\neu1812It2ivNS2oqm5dUmsxDim7lSghCHfQCyD4auk3iNEM0nB933emYXiLvM84x3WyQxngL2h4X\niS5owFp9SbDT22QrNa2HrzJb3WvT8yeS0BN4hekO1BTxghhPycbwNt9ekmy5zpZsuchstVNoa1wZ\nVlYgxzJUTFfvFbDxXTvJRr1/+p2XbA38LJctpfnSdaHpEhkPLADWM51fR7AxLfWcdC5OvQ9JttzC\n9SWRY7Z+aknTJfIocAQQmW5Zc7AR3kSyYb42ZknXhovs2vDWKLNVKYOmSyThFeA3pnuSbraRsMEp\nScqXyySpDPs6kK9uVWi6RHZllGK6fZVFnNDgZiIJb51fUkdt1ZVsucpsZSm85h/7sjkZILOBO0AG\n0/XzAxtlf9WTsOqfV+KprQaSrYGyMryr0NYmNg+HyK+BzcAXTFcJbKqm3Y4l4cOrKidQW69L14Yj\n99f23jRdIgnfAzqmmzgDbNRduYuEoxujjdRWKSlfHzpwfzlPpOkS+QbjKtNtCgUbm5pLNhI0D7ZR\nWyUdvr/QSJoukR6MZkx3wx9sXNJINrL3fr+C2nJy2NbymjRdIlcCXwHTa7FrswbY6PmOZCN63Lwo\naquE9H/1daAM01+h6RK5lbGH6WaUAhvZIZKNtJ3/zJZs9S0r5UvlgK3GHWm6RDYCmgIVmO5oe7DR\noY9kY9nBup9TW2WkfKkcKMPyzWm6RJYDKgJVmS6zKdjoc3mhdG3MjbpDbZWWbKkdsDXoDE2XSMJA\nYBjTVT8NNkr7SzbqfbfxIbVVUbLl44AtaS0/RNf0m8UQDlGdZwrYaFNOsjFc1/MGtVVB+r/8HPi/\nUtjcNSIPMbYzXdB9sNFx/s8k3DB8321J17+8ZEteB1Bqq97P7L0Isi7gDFxmuuhrYMPpW8nGw0aP\nf7VtS3kZpq2n6RKZykhgulHrwMbXLpKNwxXapEm2+lWR/i9HbNVaQtMlsiYjh+l2LwIbX+hTSXhK\n5SRW33g1ly2lZdhyD02XyBbAf4C2TJedCDYWl5FsOK3aco7WNyrnKkOltoK+Y9cByEAgBJjAdJ22\ng426VSQbh39K30/rG5UczteejTRdImOBGGA10/XVGPDhfnskG1r1pIRwNrc+VppDfx5njxA7vWpj\nnr09gtCKPUKmrkjX77Uola0dYK6Lj3FoLYL+MQI6g3tBuP9HcI99RNfrdHKD/408QwYCiELiT1co\nn5bCTv/P87O/eZr4X9wtu5m3ITkcDufFZ5iHpSxrJY16fw9eVhzO09K3auOtTxO/3u7AbbzcOMWF\nHUevxDxN/Aqper5WG6fYcK1eOv6t1Jlim7+YayJeUPol+C/VkWfJekn9IeyiEXFzIJT0F2ro9hRk\nWCNEOBt9zMsFcVj2KLpu0nyhq96D6tPnmeOcijKHz80Xusf8QPupMkh8pj8rC1+SpRNQ1qzXysIh\nsnBQHSHgnzU0XGM+2BpDw9VJOIeGq0UKPRawOFVLmc+nznxzuLYsXGuu0LUNC9eU6Z2TzPrG5Bw+\npWuVNSoLcd7OiSoB4YYk/PU7nQ/Qek6A4cQYZMABB9LlazbpoRznRUeYfPUbZetPyeKld5GvaWWO\nf04WJ0MWPisLX5KFA06Zw1qZPkQWDpKFa8jC1WXharJwVdn51JHpa8vCtWThmrKwsyzcWBZuJAs3\nlF+XMWNXP8JalIxzr1losAj3R3qZ7ihbu8twQ4t+woLfocX8Wc3hcDgcDofD4XAKl7SYHRVSWPvl\ntGwMRzb2txrDMYCXVyH1a3w4fSYbFxQilb0Bu4wja55X1gkorLK5vUjajo9X9QktYox/svrDgjDx\nf+s/kNF7wsMNNgn7e+37BLZtOqag9uUoyK/L2JwoOTfHWW5THCtLrbr1FfqN4aO57r9xL+G9EaBu\ndn0rSpPyTsaBtQRuKj22SIyFW6ELRJbfy2mp4c88DofD4Tj4XlEf/XkpqzPuLbb5NOCJ6Jhs+ySD\n//8czr9w/8Xsr3Cc9Q1ctFG3PYknybYnMni5cTj/RtvY61otDR0PQ8bBDGFt3mG8jfkvtOvv5eqf\n6c/L5Rlc0/uOXVGfxh4QLuUn4qNABwivZLKnj4gHgawBcgXIN9SOz7vjcIobxH8wuGG69E3P8tcG\nSLou7sZnVkILf5Quje3WB95j/aNrW2lRRjzdn2xM5xIZB9nskAH7+5HtnVWyJX10HNQDIW5mmoBW\nSmtyLF0n4tEQZ0RXEfv6kDTmfWqOcz2WtOGS15jjeElxBo8zx7khpTMmslB9XDpBI070TJTG3t0H\npPVRhPrSeMIvFkrvyj/Pj0S3pfOt/fYlrJbOc1LCCLRMOr8k90zcyofEK/fGCJQj6XbezcTDpHhb\nN41m+Zj35QXsI+k6jxzFyihVm4xnSzaqV5mCZkm6zzsewE+kMp92cSr6SdK932G/ZFdAPmenoq8k\nXSLofCVdmQkh0veWRVy243ncW9I9mfMxWi7FGzokA/tJdl9/4s/+z+xyZ7G3FG/UH5+gx1K8j785\nK52fgI4P+ARFxub1fhvO3282fHVhVyayfpeRucrsL4v2DymzQbzMOJyXrA6rriAwnyXxVWabfZaH\nm5afnZP7GLoWTV74BNs67kV7dm78iPq2H0nPTrlPlPh2I26LOJKslYbEzcIadsyS8zjRYsw/58X1\nWbRhYxtS8Cir9+RMXj7PtN/27wpZrD5/T5GfJcxc92djjY7zciz+xPTyJ2tKPWLXCVmH9Ra0CYYQ\npP2CdF30BEroBdSNzQGrCO2nX2B7AC9DDodTbN6b16qIbF1q8jy8BfwBXJnbpYExzobr5vCzeQYv\nqGC0eZjYAg45ULf++zKtW52G57ll3Sqv9bPHqH+/O0VF+zMElUnfKSK61REFdpXGc+QYnjZPm6fN\n0+ZpP33aHIf9+mdz+fU/eQ71kK8rn5fa5cnoiFW7fAr/nzgcDofD4XA4HA6Hw+E85zE+O66MY+Mj\nh1v0qxjwQ6t+FW2RPP+eV6az8w+SnXvvAp27IWZWhf1sPEYaS/NQrn6mYjWPQd3wnvHbTaMBDZsb\n2A1QA78ByV6SP+1hjzeIzJpLJYfD4XA4HA6n+HM+pnytubpgtALCfwFknfwswIWNvyoFYOC6jn47\nYBlI4h9drbP8lgDH0pd93KKNUVYj4jBeLk/Zjrl7WWDtwV5Pddw5Nh7vvMW8yXFW7eKXt1xDr3g4\nUK6kDW39beEpvDyhPCf8bJxzRtZO6GJjfurTEIHoN5u1pL9CvbCisS2P/UQc5EO/v3zch5b/abYm\ng8+tFHdyrPt/H0tyhOwc+im0y+O9mPH683jFOp55LYjIIAGNx0q/V/9v8bEd/S2yxsOFx5uFi86r\npqD2sxdo3EtX/s5wf1PT6Pqrx+7dv2vCGXi+jbmiZu8iZWucG/BUJP9m1n5GYT7f75jqIW6Kj7sQ\nc+H9m0n+aCGEA4BkqC83J3O49ALaBHILyHqxAvotjs45CI+jYwwT4mi9e2IcnQdRK47WyR8m0flg\nO38Z+ClJX1is70HkwVtObkT2b7h9MZHTmneU7C86OFeSSSUp72AzEUBvnIWcZ7ZDTngV1OPHoP/8\nX2spvk8yXWuDzEd7pLPMU+aJjJF/Lnvs6dK/dGep7TCgN+rSj/bPV3ZP0zReNVJaa4O0Dy7u0Xsv\nLDdP2pecT1n1Vvxf+NrUk3bLAVttm/zaPgW8Nv7yz9sXsT9c6b3aa5ItfYI4Br0p287vO4rDHc6L\nayGuWfbnICqDgcxgEZfoU7D0/gHKk+ent4h/GELrSgU9x0XIfI6tm+T
